name: 'swift-format-lint'
description: 'Lints files passed into this action using swift-format'
inputs:
  file-paths: # List of file paths to lint
    description: "List of file paths to lint"
    required: true
  excludes: # List of file paths to exclude
    description: "List of file paths to eclude"
    required: false
  exclude-types: # List of types to exclude
    description: "LIst of types to exclude"
    required: false
  github-token:
    description: 'GITHUB_TOKEN'
runs:
  using: 'node12'
  main: 'index.js'

