on: [pull_request]

jobs:
  swift-format-lint:
    runs-on: ubuntu-latest
    name: Swift-Format
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore swift build cache
      - uses: actions/cache@v1
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: swift build
        run: |
          if [ -d ".build" ]; then
            echo 'using cache'
          else
            git clone -b swift-5.2-branch https://github.com/apple/swift-format.git
            cd swift-format
            swift build --disable-sandbox -c release
            sudo cp -f .build/release/swift-format /usr/local/bin/swift-format
          fi
      - name: Lint
        uses: ./ # Uses an action in the root directory
        id: swift-format-lint
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          excludes: '["whatev"]'